spring:
  application:
    name: chat-chit-flutter
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_chit_db
    username: root
    password: root
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082